In [5]:
#!/usr/bin/env python3
"""
Fraud Detection Analysis
=========================
Identifies accounts with unusual patterns compared to peers.
Used by compliance team for quarterly risk assessment.
"""

import psycopg2
import time
from datetime import datetime

DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "database": "app_db",
    "user": "app_user",
    "password": "StrongPassword123!"
}


def run_fraud_analysis():
    """Analyze accounts for suspicious patterns."""
    print("=" * 60)
    print("Fraud Detection Analysis")
    print("=" * 60)
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("-" * 60)
    
    query = """
    WITH account_data AS (
        SELECT 
            a.aid,
            a.bid,
            a.abalance,
            b.bbalance,
            NTILE(100) OVER (ORDER BY a.abalance) as percentile
        FROM pgbench_accounts a
        JOIN pgbench_branches b ON a.bid = b.bid
    ),
    peer_comparison AS (
        SELECT 
            a1.aid as account_id,
            a1.bid as branch_id,
            a1.abalance as balance,
            a2.aid as peer_id,
            a2.abalance as peer_balance,
            ABS(a1.abalance - a2.abalance) as difference,
            CASE 
                WHEN a1.abalance > 0 AND a2.abalance > 0 
                THEN LEAST(a1.abalance, a2.abalance)::FLOAT / 
                     GREATEST(a1.abalance, a2.abalance)
                ELSE 0 
            END as similarity
        FROM account_data a1
        JOIN account_data a2 ON a1.bid = a2.bid 
            AND a1.aid != a2.aid
            AND ABS(a1.percentile - a2.percentile) <= 5
        WHERE a1.aid <= 80000 AND a2.aid <= 80000
    ),
    risk_metrics AS (
        SELECT 
            account_id,
            branch_id,
            balance,
            COUNT(DISTINCT peer_id) as peer_count,
            AVG(difference) as avg_diff,
            AVG(similarity) as avg_similarity,
            STDDEV(difference) as diff_volatility
        FROM peer_comparison
        GROUP BY account_id, branch_id, balance
        HAVING COUNT(DISTINCT peer_id) >= 10
    ),
    risk_scores AS (
        SELECT 
            r.*,
            CASE 
                WHEN avg_similarity < 0.3 THEN 'HIGH_RISK'
                WHEN avg_similarity < 0.5 THEN 'MEDIUM_RISK'
                WHEN avg_similarity < 0.7 THEN 'LOW_RISK'
                ELSE 'NORMAL'
            END as risk_level,
            (1 - avg_similarity) * 100 as anomaly_score
        FROM risk_metrics r
    )
    SELECT 
        account_id,
        branch_id,
        balance,
        peer_count,
        avg_diff,
        avg_similarity,
        anomaly_score,
        risk_level
    FROM risk_scores
    WHERE risk_level IN ('HIGH_RISK', 'MEDIUM_RISK')
    ORDER BY anomaly_score DESC
    LIMIT 500;
    """
    
    try:
        print("Connecting...")
        conn = psycopg2.connect(**DB_CONFIG)
        cursor = conn.cursor()
        print("Running fraud detection scan...")
        
        start_time = time.time()
        cursor.execute(query)
        results = cursor.fetchall()
        elapsed = time.time() - start_time
        
        print("\n" + "=" * 60)
        print("Analysis Complete")
        print(f"Duration: {elapsed:.2f}s ({elapsed/60:.2f} min)")
        print(f"Suspicious Accounts: {len(results)}")
        print("=" * 60)
        
        if results:
            high = len([r for r in results if r[7] == 'HIGH_RISK'])
            med = len([r for r in results if r[7] == 'MEDIUM_RISK'])
            print(f"\nRisk Summary: HIGH={high}, MEDIUM={med}")
            
            print("\nTop Flagged Accounts:")
            for row in results[:5]:
                print(f"  Account {row[0]}: Score={row[6]:.1f}, Risk={row[7]}")
        
        cursor.close()
        conn.close()
        
    except psycopg2.Error as e:
        print(f"Error: {e}")
        raise


if __name__ == "__main__":
    run_fraud_analysis()

============================================================
Fraud Detection Analysis
============================================================
Started: 2026-02-03 00:48:48
------------------------------------------------------------
Connecting...
Running fraud detection scan...
Error: could not write to file "base/pgsql_tmp/pgsql_tmp2183329.165": No space left on device

DiskFull: could not write to file "base/pgsql_tmp/pgsql_tmp2183329.165": No space left on device

# Database Query & Load Testing Notebook

This notebook connects to the local PostgreSQL database `app_db` and executes queries for testing purposes.

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

# Database Connection String
DB_URI = "postgresql://app_user:StrongPassword123!@localhost:5432/app_db"

# Create Engine
engine = create_engine(DB_URI)

def run_query(query):
    """Executes a SQL query and returns the result as a DataFrame."""
    with engine.connect() as conn:
        return pd.read_sql(text(query), conn)

print("Database connection established.")

Database connection established.

In [2]:
import pandas as pd
from sqlalchemy import create_engine, text, inspect
from IPython.display import display, Markdown

# Database connection
DATABASE_URL = "postgresql+psycopg2://kavach_readonly:kavach_readonly123@10.10.90.94:5434/alerts"
engine = create_engine(DATABASE_URL)

print("✓ Connected to database")

✓ Connected to database

In [3]:
import pandas as pd
from sqlalchemy import create_engine, inspect, text
from IPython.display import display, Markdown

# Database connection
DATABASE_URL = "postgresql+psycopg2://kavach_readonly:kavach_readonly123@10.10.90.94:5434/alerts"
engine = create_engine(DATABASE_URL)
inspector = inspect(engine)

print("✓ Connected to database")

# Get all schemas except system ones
schemas = [
    s for s in inspector.get_schema_names()
    if s not in ("information_schema", "pg_catalog")
]

for schema in schemas:
    tables = inspector.get_table_names(schema=schema)

    for table in tables:
        display(Markdown(f"## 📦 `{schema}.{table}`"))

        # ---- 1. TABLE SCHEMA ----
        columns = inspector.get_columns(table, schema=schema)
        schema_df = pd.DataFrame([
            {
                "column": c["name"],
                "type": str(c["type"]),
                "nullable": c["nullable"],
                "default": c["default"]
            }
            for c in columns
        ])

        display(Markdown("### 🧱 Schema"))
        display(schema_df)

        # ---- 2. FIND BEST ORDER COLUMN ----
        column_names = [c["name"] for c in columns]

        preferred_time_cols = [
            "updated_at", "created_at", "inserted_at", "event_time", "timestamp"
        ]
        order_col = next(
            (c for c in preferred_time_cols if c in column_names),
            None
        )

        if not order_col:
            pk = inspector.get_pk_constraint(table, schema=schema)
            if pk and pk.get("constrained_columns"):
                order_col = pk["constrained_columns"][0]

        # ---- 3. FETCH LAST 5 ROWS ----
        if order_col:
            query = text(f"""
                SELECT *
                FROM {schema}.{table}
                ORDER BY {order_col} DESC
                LIMIT 5
            """)
        else:
            query = text(f"""
                SELECT *
                FROM {schema}.{table}
                LIMIT 5
            """)

        try:
            df = pd.read_sql(query, engine)
            display(Markdown("### 📄 Latest 5 rows"))
            display(df)
        except Exception as e:
            display(Markdown(f"❌ Error reading data: `{e}`"))

✓ Connected to database

## 📦 `public.alert_predictions`

### 🧱 Schema

                   column              type  nullable default
0           prediction_id              UUID     False    None
1                as_of_ts         TIMESTAMP     False    None
2                hostname              TEXT     False    None
3               timestamp         TIMESTAMP     False    None
4         top_class_index           INTEGER      True    None
5            top_label_id           INTEGER      True    None
6   top_label_description              TEXT      True    None
7          top_class_prob  DOUBLE PRECISION      True    None
8                features             JSONB      True    None
9        shap_explanation             JSONB      True    None
10               severity           INTEGER      True    None
11                service              TEXT      True    None
12             root_cause              TEXT      True    None
13         recommendation              TEXT      True    None
14                 action              TEXT      True    None
15             created_at         TIMESTAMP      True   now()
16                summary              TEXT      True    None
17      impact_assessment              TEXT      True    None
18          urgency_level              TEXT      True    None
19     recommended_action              TEXT      True    None
20            run_actions             JSONB      True    None

### 📄 Latest 5 rows

,prediction_id,as_of_ts,hostname,timestamp,top_class_index,top_label_id,top_label_description,top_class_prob,features,shap_explanation,...,service,root_cause,recommendation,action,created_at,summary,impact_assessment,urgency_level,recommended_action,run_actions
0,06d77b92-1ab4-4fd3-8104-86329d8bc483,2026-02-03 05:49:10.346152+00:00,Galaxy-Internal-Proxy,2026-02-03 05:49:10.336011+00:00,43,43,HTTP poller utilization will be high,0.790664,"{'no_alert': 0.08297482889720387, '{HOST.NAME}...",{'features': ['zabbix_process_discovery_manage...,...,Compute/VM,Resource exhaustion due to high load,"Check recent logs, restart web service, and cl...",Investigate HTTP poller utilization and optimi...,2026-02-03 05:49:10.370452+00:00,Galaxy-Internal-Proxy experiencing high HTTP p...,Website loading slowly,Fix within 1 hour,Restart web service,"[{'risk': 'Low', 'title': 'Restart Web Service..."
1,a8400fb5-a64b-4544-b2d8-c32309e3b9c8,2026-02-03 05:48:09.021817+00:00,Galaxy-Internal-Proxy,2026-02-03 05:48:09.011890+00:00,43,43,HTTP poller utilization will be high,0.998662,"{'no_alert': 0.0005286112842961322, '{HOST.NAM...",{'features': ['zabbix_process_discovery_manage...,...,Compute/VM,Resource exhaustion due to high load,"Check recent logs, restart web service, and cl...",Investigate HTTP poller utilization and take c...,2026-02-03 05:48:09.046527+00:00,Galaxy-Internal-Proxy experiencing high HTTP p...,Website loading slowly,Fix within 1 hour,Restart web service,"[{'risk': 'Low', 'title': 'Restart Web Service..."
2,95cfc2dc-b5d2-4dfe-9e6c-c94ca7211e1e,2026-02-03 05:46:09.567767+00:00,Galaxy-Internal-Proxy,2026-02-03 05:46:09.557745+00:00,43,43,HTTP poller utilization is high (Disaster),0.760240,"{'no_alert': 0.16338414267826554, '{HOST.NAME}...",{'features': ['zabbix_process_discovery_manage...,...,Compute/VM,Automated analysis unavailable - manual review...,Check system logs and metrics dashboard.,Monitor system,2026-02-03 05:46:09.592863+00:00,No summary available.,,,,None
3,7f8c7f20-96f6-4baa-8281-456bfd6aa35a,2026-02-03 05:06:10.416900+00:00,Galaxy-Internal-Proxy,2026-02-03 05:06:10.407023+00:00,43,43,HTTP poller utilization is high (Disaster),0.984326,"{'no_alert': 0.014774689800444048, '{HOST.NAME...",{'features': ['zabbix_process_discovery_manage...,...,Compute/VM,Automated analysis unavailable - manual review...,Check system logs and metrics dashboard.,Monitor system,2026-02-03 05:06:10.441847+00:00,No summary available.,,,,None
4,ed5fac00-c08e-4b77-8ab6-52584fd7bac3,2026-02-03 05:05:11.759498+00:00,Galaxy-Internal-Proxy,2026-02-03 05:05:11.749111+00:00,43,43,HTTP poller utilization is high (Disaster),0.959428,"{'no_alert': 0.0224033655000498, '{HOST.NAME} ...",{'features': ['zabbix_process_discovery_manage...,...,Compute/VM,Automated analysis unavailable - manual review...,Check system logs and metrics dashboard.,Monitor system,2026-02-03 05:05:11.784546+00:00,No summary available.,,,,None

## 📦 `public.host_details`

### 🧱 Schema

,column,type,nullable,default
0,id,INTEGER,False,"nextval('""public"".host_details_id_seq'::regclass)"
1,host_name,TEXT,False,None
2,visible_name,TEXT,True,None
3,category,TEXT,False,None
4,alert_count,INTEGER,True,0
5,prediction_count,INTEGER,True,0
6,healthy,INTEGER,True,1
7,updated_at,TIMESTAMP,True,now()
8,alert_low,INTEGER,True,0
9,alert_medium,INTEGER,True,0
10,alert_high,INTEGER,True,0
11,alert_critical,INTEGER,True,0
12,pred_low,INTEGER,True,0
13,pred_medium,INTEGER,True,0
14,pred_high,INTEGER,True,0
15,pred_critical,INTEGER,True,0
16,importance,INTEGER,True,10
17,ip_address,VARCHAR(45),True,None
18,ansible_configured,BOOLEAN,False,false

### 📄 Latest 5 rows

,id,host_name,visible_name,category,alert_count,prediction_count,healthy,updated_at,alert_low,alert_medium,alert_high,alert_critical,pred_low,pred_medium,pred_high,pred_critical,importance,ip_address,ansible_configured
0,1564,Ad Server - integrity,Ad Server - integrity,Infrastructure,0,1,0,2026-02-03 11:23:01.995782+00:00,0,0,0,0,0,0,0,0,10,None,False
1,1598,AI_Team_91,AI_Team_91,Infrastructure,0,0,1,2026-02-03 11:23:01.995557+00:00,0,0,0,0,0,0,0,0,10,None,False
2,1596,AI_Team_92,AI_Team_92,Infrastructure,0,0,1,2026-02-03 11:23:01.995349+00:00,0,0,0,0,0,0,0,0,10,10.10.90.92,True
3,1595,AI_Team_93,AI_Team_93,Infrastructure,0,0,1,2026-02-03 11:23:01.995141+00:00,0,0,0,0,0,0,0,0,10,None,False
4,1593,Backup_Cohesity,Backup_Cohesity,Infrastructure,0,0,1,2026-02-03 11:23:01.994931+00:00,0,0,0,0,0,0,0,0,10,None,False

## 📦 `public.causal_runs`

### 🧱 Schema

,column,type,nullable,default
0,id,INTEGER,False,"nextval('""public"".causal_runs_id_seq'::regclass)"
1,run_id,UUID,True,gen_random_uuid()
2,trigger_reason,TEXT,True,None
3,started_at,TIMESTAMP,True,now()
4,completed_at,TIMESTAMP,True,None
5,status,TEXT,True,'running'::text
6,root_causes,JSONB,True,None
7,llm_narrative,TEXT,True,None
8,graph_nodes,JSONB,True,None
9,graph_edges,JSONB,True,None
10,node_count,INTEGER,True,None
11,edge_count,INTEGER,True,None
12,root_count,INTEGER,True,None
13,host_insights,JSONB,True,None
14,window_minutes,INTEGER,True,None

### 📄 Latest 5 rows

,id,run_id,trigger_reason,started_at,completed_at,status,root_causes,llm_narrative,graph_nodes,graph_edges,node_count,edge_count,root_count,host_insights,window_minutes
0,619,bbfb72ee-3d89-49d7-8084-e53eedf0620c,scheduled,2026-02-03 05:05:17.910822+00:00,2026-02-03 05:05:17.911542+00:00,completed,[Mysql Database||Number of installed packages ...,### AI Root Cause Insights Summary\n\n#### Roo...,[{'id': 'Galaxy-Internal-Proxy||HTTP poller ut...,[{'dst': 'KLaptop - Active Agent||KLaptop will...,7,9,3,{'RoshanLaptop||RoshanLaptop will be restarted...,1440
1,618,e6d021c9-a315-4950-92aa-86056bf82ebd,scheduled,2026-02-03 04:04:16.767459+00:00,2026-02-03 04:04:16.768207+00:00,completed,[Mysql Database||Number of installed packages ...,### AI Root Cause Insights Summary\n\n**Root N...,[{'id': 'Galaxy-Internal-Proxy||HTTP poller ut...,[{'dst': 'KLaptop - Active Agent||KLaptop will...,7,9,3,{'RoshanLaptop||RoshanLaptop will be restarted...,1440
2,617,15c4916d-07b8-4887-ab9c-d0ee767f8e74,scheduled,2026-02-03 03:03:17.676069+00:00,2026-02-03 03:03:17.676872+00:00,completed,[Mysql Database||Number of installed packages ...,### AI Root Cause Insights Summary\n\n#### Roo...,[{'id': 'Galaxy-Internal-Proxy||HTTP poller ut...,[{'dst': 'KLaptop - Active Agent||KLaptop will...,7,9,3,{'RoshanLaptop||RoshanLaptop will be restarted...,1440
3,616,ac3ed352-2f39-4835-9522-271f2d9f92ca,scheduled,2026-02-03 02:02:15.941302+00:00,2026-02-03 02:02:15.942047+00:00,completed,[Mysql Database||Number of installed packages ...,### AI Root Cause Insights Summary\n\n**Root N...,[{'id': 'Galaxy-Internal-Proxy||HTTP poller ut...,[{'dst': 'RoshanLaptop||RoshanLaptop will be r...,7,9,3,{'RoshanLaptop||RoshanLaptop will be restarted...,1440
4,615,cb5bc516-c36c-450e-a43c-2d62f380bc90,scheduled,2026-02-03 01:01:12.301411+00:00,2026-02-03 01:01:12.302213+00:00,completed,[Mysql Database||Number of installed packages ...,### AI Root Cause Insights Summary\n\n#### Roo...,[{'id': 'Galaxy-Internal-Proxy||HTTP poller ut...,[{'dst': 'RoshanLaptop||RoshanLaptop will be r...,7,8,3,{'RoshanLaptop||RoshanLaptop will be restarted...,1440

## 📦 `public.live_alerts`

### 🧱 Schema

            column       type  nullable         default
0         alert_id       TEXT     False            None
1        timestamp  TIMESTAMP     False            None
2             host       TEXT      True            None
3        component       TEXT      True            None
4           domain       TEXT      True            None
5         severity    INTEGER      True            None
6    issue_summary       TEXT      True            None
7       root_cause       TEXT      True            None
8   recommendation       TEXT      True            None
9           action       TEXT      True            None
10          status       TEXT      True            None
11    acknowledged    BOOLEAN      True            None
12          source       TEXT      True  'zabbix'::text
13      updated_at  TIMESTAMP      True           now()
14         metrics      JSONB      True            None

### 📄 Latest 5 rows

,alert_id,timestamp,host,component,domain,severity,issue_summary,root_cause,recommendation,action,status,acknowledged,source,updated_at,metrics
0,29000236,2026-02-03 05:52:06+00:00,KAMAL-PATEL,,None,1,Interface Intel(R) Wi-Fi 6 AX200 160MHz(Wi-Fi)...,,,,ACTIVE,False,zabbix,2026-02-03 05:52:53.342789+00:00,"{'used_memory': '12966281216 B', 'total_memory..."
1,29000093,2026-02-03 05:51:03+00:00,MANAGEENGINEAPP,,None,3,"""AwsReplicationVolumeUpdaterService"" (AwsRepli...",Enriching...,,,ACTIVE,False,zabbix,2026-02-03 05:52:53.342789+00:00,"{'used_memory': '10126446592 B', 'total_memory..."
2,28999691,2026-02-03 05:48:52+00:00,KAMAL-PATEL,,None,3,"""GoogleUpdaterService144.0.7547.0"" (Google Upd...",Automated analysis unavailable - manual review...,Check Zabbix console and system logs.,Monitor system,ACTIVE,False,zabbix,2026-02-03 05:52:53.342789+00:00,"{'used_memory': '12966281216 B', 'total_memory..."
3,28999690,2026-02-03 05:48:51+00:00,KAMAL-PATEL,,None,3,"""GoogleUpdaterInternalService144.0.7547.0"" (Go...",Enriching...,,,ACTIVE,False,zabbix,2026-02-03 05:52:53.342789+00:00,"{'used_memory': '12966281216 B', 'total_memory..."
4,28999473,2026-02-03 05:47:13+00:00,RoshanLaptop,,None,3,"""AppXSvc"" (AppX Deployment Service (AppXSVC)) ...",The AppX Deployment Service (AppXSVC) is not r...,Check the service configuration and dependenci...,Investigate and potentially restart the AppX D...,ACTIVE,False,zabbix,2026-02-03 05:52:53.342789+00:00,"{'used_memory': '6850822144 B', 'total_memory'..."

## 📦 `public.top_risky_components`

### 🧱 Schema

,column,type,nullable,default
0,id,INTEGER,False,"nextval('""public"".top_risky_components_id_seq'..."
1,host,TEXT,False,None
2,alert_count,INTEGER,False,None
3,percentage,"NUMERIC(5, 2)",False,None
4,rank,INTEGER,False,None
5,updated_at,TIMESTAMP,True,now()

### 📄 Latest 5 rows

,id,host,alert_count,percentage,rank,updated_at
0,11703,RoshanLaptop,5,45.45,1,2026-02-02 13:38:04.588462+00:00
1,11704,KAMAL-PATEL,3,27.27,2,2026-02-02 13:38:04.588462+00:00
2,11705,AI_Team_92,1,9.09,3,2026-02-02 13:38:04.588462+00:00

## 📦 `public.domain_health_history`

### 🧱 Schema

,column,type,nullable,default
0,id,INTEGER,False,"nextval('""public"".domain_health_history_id_seq..."
1,category,TEXT,False,None
2,health_score,INTEGER,True,None
3,alert_count,INTEGER,True,None
4,prediction_count,INTEGER,True,None
5,healthy_count,INTEGER,True,None
6,total_count,INTEGER,True,None
7,recorded_at,TIMESTAMP,True,now()

### 📄 Latest 5 rows

,id,category,health_score,alert_count,prediction_count,healthy_count,total_count,recorded_at
0,197739,Services,61,3,1,3,7,2026-02-03 05:53:02.000327+00:00
1,197738,Network,96,0,9,4,13,2026-02-03 05:53:02.000327+00:00
2,197737,Infrastructure,92,3,44,87,133,2026-02-03 05:53:02.000327+00:00
3,197736,Databases,50,2,2,2,4,2026-02-03 05:53:02.000327+00:00
4,197735,Applications,100,0,5,17,22,2026-02-03 05:53:02.000327+00:00

## 📦 `public.domain_health`

### 🧱 Schema

                  column       type  nullable default
0               category       TEXT     False    None
1            total_count    INTEGER      True       0
2          healthy_count    INTEGER      True       0
3            alert_count    INTEGER      True       0
4         new_host_count    INTEGER      True       0
5           health_score    INTEGER      True     100
6             updated_at  TIMESTAMP      True   now()
7       prediction_count    INTEGER      True       0
8  previous_health_score    INTEGER      True    None
9     last_hour_snapshot  TIMESTAMP      True    None

### 📄 Latest 5 rows

,category,total_count,healthy_count,alert_count,new_host_count,health_score,updated_at,prediction_count,previous_health_score,last_hour_snapshot
0,Services,7,3,3,0,61,2026-02-03 11:23:01.999457+00:00,1,100,2026-01-27 14:57:01.792406+00:00
1,Network,13,4,0,0,96,2026-02-03 11:23:01.999207+00:00,9,95,2026-02-03 11:14:02.370257+00:00
2,Infrastructure,133,87,3,0,92,2026-02-03 11:23:01.998953+00:00,44,91,2026-02-03 08:32:01.855777+00:00
3,Databases,4,2,2,0,50,2026-02-03 11:23:01.998684+00:00,2,0,2026-02-02 10:59:02.123810+00:00
4,Applications,22,17,0,0,100,2026-02-03 11:23:01.998344+00:00,5,96,2026-01-19 09:10:01.740035+00:00

## 📦 `public.alembic_version`

### 🧱 Schema

        column         type  nullable default
0  version_num  VARCHAR(32)     False    None

### 📄 Latest 5 rows

    version_num
0  a1b2c3d4e5f6

## 📦 `public.otel_predictions`

### 🧱 Schema

              column              type  nullable default
0      prediction_id              UUID     False    None
1       service_name              TEXT     False    None
2           hostname              TEXT     False    None
3          timestamp         TIMESTAMP     False    None
4    predicted_state              TEXT     False    None
5         confidence  DOUBLE PRECISION      True    None
6           features             JSONB      True    None
7   shap_explanation             JSONB      True    None
8           severity           INTEGER      True    None
9         root_cause              TEXT      True    None
10    recommendation              TEXT      True    None
11           summary              TEXT      True    None
12        created_at         TIMESTAMP      True   now()

### 📄 Latest 5 rows

,prediction_id,service_name,hostname,timestamp,predicted_state,confidence,features,shap_explanation,severity,root_cause,recommendation,summary,created_at
0,d6416575-3705-4f75-acae-a8a1e235283e,kavach-backend,AI_Team_94,2026-02-02 13:04:00+00:00,healthy,0.999972,"{'otel_error_rate': 0.0, 'otel_error_count': 0...","{'features': ['otel_duration_p95_rstd15', 'ote...",1,otel_duration_p95_rstd15=0.41; otel_request_co...,No action required. Service operating normally.,healthy predicted for kavach-backend on AI_Tea...,2026-02-02 18:34:38.880780+00:00
1,047b7963-5b1a-41b9-8b76-36cf38fb8482,kavach-backend,AI_Team_94,2026-02-02 12:48:00+00:00,throughput_drop,0.999954,"{'otel_error_rate': 0.0, 'otel_error_count': 0...","{'features': ['otel_request_count_rmean15', 'o...",2,otel_request_count_rmean15=110.80; otel_reques...,Request throughput has dropped significantly. ...,throughput_drop predicted for kavach-backend o...,2026-02-02 18:18:11.411120+00:00

## 📦 `public.otel_service_snapshots`

### 🧱 Schema

                   column              type  nullable default
0             snapshot_id              UUID     False    None
1            service_name              TEXT     False    None
2                hostname              TEXT     False    None
3               timestamp         TIMESTAMP     False    None
4           request_count           INTEGER      True    None
5             error_count           INTEGER      True    None
6              error_rate  DOUBLE PRECISION      True    None
7            duration_p50  DOUBLE PRECISION      True    None
8            duration_p95  DOUBLE PRECISION      True    None
9            duration_p99  DOUBLE PRECISION      True    None
10         pg_connections           INTEGER      True    None
11      mysql_connections           INTEGER      True    None
12        active_requests           INTEGER      True    None
13         db_query_count           INTEGER      True    None
14       db_duration_mean  DOUBLE PRECISION      True    None
15        predicted_state              TEXT      True    None
16  prediction_confidence  DOUBLE PRECISION      True    None
17           summary_text              TEXT      True    None
18             created_at         TIMESTAMP      True   now()

### 📄 Latest 5 rows

,snapshot_id,service_name,hostname,timestamp,request_count,error_count,error_rate,duration_p50,duration_p95,duration_p99,pg_connections,mysql_connections,active_requests,db_query_count,db_duration_mean,predicted_state,prediction_confidence,summary_text,created_at
0,292945d9-0304-47ed-8733-fdcf3932498e,kavach-backend,AI_Team_94,2026-02-02 13:04:00+00:00,69,0,0.0,0.311265,6.526957,8.769026,0,0,0,48,0.960709,healthy,0.999972,**APPLICATION TELEMETRY (OpenTelemetry):**\nSe...,2026-02-02 18:34:38.891999+00:00
1,39fffb5f-91d4-443b-b25f-83055e7fceab,kavach-backend,AI_Team_94,2026-02-02 12:48:00+00:00,3,0,0.0,0.040617,1.108174,1.203069,0,0,0,0,0.000000,throughput_drop,0.999954,**APPLICATION TELEMETRY (OpenTelemetry):**\nSe...,2026-02-02 18:18:11.420972+00:00

## 📦 `public.problem_autofix_details`

### 🧱 Schema

,column,type,nullable,default
0,problem_id,INTEGER,False,"nextval('""public"".problem_autofix_details_prob..."
1,problem,TEXT,False,None
2,host_type,VARCHAR(50),False,None
3,autofix_details,TEXT,True,None
4,created_at,TIMESTAMP,False,now()
5,updated_at,TIMESTAMP,False,now()
6,action_steps,JSONB,True,None
7,estimated_duration_seconds,INTEGER,True,None
8,rollback_available,BOOLEAN,True,true
9,description,TEXT,True,None

### 📄 Latest 5 rows

,problem_id,problem,host_type,autofix_details,created_at,updated_at,action_steps,estimated_duration_seconds,rollback_available,description
0,3,System time is out of sync,windows,time_sync.yml,2026-01-23 11:47:41.337477+00:00,2026-01-23 11:47:41.337477+00:00,"[{'icon': 'clock', 'step': 1, 'title': 'Check ...",15,False,Synchronizes system time with NTP server and r...
1,1,VMware Tools is not running,linux,VMTools_Win_Lin.yml,2026-01-23 11:41:50.896684+00:00,2026-01-23 11:41:50.896684+00:00,"[{'icon': 'search', 'step': 1, 'title': 'Check...",30,True,Restarts the VMware Tools service to restore V...
2,2,System time is out of sync,linux,time_sync.yml,2026-01-23 11:41:50.896684+00:00,2026-01-23 11:41:50.896684+00:00,"[{'icon': 'clock', 'step': 1, 'title': 'Check ...",15,False,Synchronizes system time with NTP server and r...

## 1. Sort Data Query
Retreiving the top 10 accounts with the highest balance. This involves scanning and sorting.

In [4]:
query_sort = """
SELECT aid, bid, abalance 
FROM pgbench_accounts 
ORDER BY abalance DESC 
LIMIT 10;
"""

df_sort = run_query(query_sort)
df_sort

ProgrammingError: (psycopg2.errors.UndefinedTable) relation "pgbench_accounts" does not exist
LINE 3: FROM pgbench_accounts
             ^

[SQL:
SELECT aid, bid, abalance
FROM pgbench_accounts
ORDER BY abalance DESC
LIMIT 10;
]
(Background on this error at: https://sqlalche.me/e/20/f405)

## 2. Long Running Query
This query sleeps for 30 seconds to simulate a slow database operation.  
**Note:** Verification of this cell will take 30 seconds.

In [ ]:
long_running_query = "SELECT pg_sleep(30) as slept_for_30_seconds;"

print("Starting sleep query...")
df_long = run_query(long_running_query)
print("Query completed.")
df_long